# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0003_auto_20170220_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
    ]
