# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0004_auto_20170220_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
